---
default_install_hook_types: [pre-commit, pre-push, commit-msg]
default_stages: [pre-commit, pre-push]
repos:
  - repo: .
    rev: v0.1.0
    hooks:
      - id: cocogitto-check
      - id: cocogitto-verify
